### ISSUE TITLE
Redirects all subdomains

### ISSUE THREAD

**Issue by jenius** [bosmacs/KeepOnSmiling#3]
If you go to `developer.amazon.com`, which hosts many of their web services and docs, it will redirect to `smile` and end up at a broken page. The redirect should only happen from the bare domain level, not on any other subdomains.

I'm going to put in a PR to fix this, issue just here as documentation and a reminder!

**Comment by iheijoushin** [comment]
Verified that the issue describes occurs on most recent build with payments.amazon.com (used by many companies including HumbleBundle.com).

Jenius - have you had a chance to submit your fix?

**Comment by jenius** [comment]
Yeah it's referenced above and was recently merged

**Comment by iheijoushin** [comment]
Thanks for replying. It appears we're just waiting on an updated release that includes the security certs from Apple. Thanks!

**Comment by bosmacs** [comment]
Closing as this should be included in the new [1.1 release](https://github.com/bosmacs/KeepOnSmiling/releases/tag/v1.1). Apologies for taking so long to get around to making a new safariextz.
