### ISSUE TITLE
Include installation instructions in README

### ISSUE THREAD

**Issue by jmegs** [bosmacs/KeepOnSmiling#9]
having trouble packaging the file into a format acceptable for Safari 10. process in the README will help this get adopted => more charity money.

**Comment by ghost** [comment]
You should just be able to download [the file here](https://github.com/bosmacs/KeepOnSmiling/releases/download/v1.2/KeepOnSmiling.safariextz) and install it. Also check out [this official link](https://support.apple.com/en-us/HT203051) from Apple.

I'm going to create a pull request referencing this issue for installation instructions as well.

**Comment by dfleck** [comment]
But neither "Open in Desktop" or "Download ZIP" results in a doubleclickable install file, only the link above does. And a recent Burning Man email blast included a link to this project.
